from pydantic import BaseModel, Field
from typing import List


# -----------------------------------------------------------------------------
# Request Model: What the user sends to our API
# -----------------------------------------------------------------------------
class ResearchRequest(BaseModel):
    """
    Data sent by the user to start a research task.
    """
    query: str = Field(
        ...,
        description="The research question or topic",
        examples=["Compare PostgreSQL, MongoDB and DynamoDB for an e-commerce backend"]
    )


# -----------------------------------------------------------------------------
# Response Model: What our API sends back to the user
# -----------------------------------------------------------------------------
class ResearchResponse(BaseModel):
    """
    Data returned to the user after running the research workflow.
    In Phase 2, this includes the sub-questions generated by the Planner.
    """
    status: str = Field(
        ...,
        description="Current status of the research workflow",
        examples=["planned"]
    )
    query: str = Field(
        ...,
        description="Echoes back the research query received"
    )
    sub_questions: List[str] = Field(
        default_factory=list,
        description="The broken-down sub-questions produced by the Planner node"
    )
    message: str = Field(
        ...,
        description="Human-readable explanation of current status"
    )
