from typing import TypedDict, List


# -----------------------------------------------------------------------------
# ResearchState: The Central Memory of our Agent Graph
# -----------------------------------------------------------------------------
# In LangGraph, "State" is a shared dictionary that travels from node to node.
# Each node reads what it needs from the state, does some work (like planning
# or searching), and returns a dictionary with new or updated values.
# -----------------------------------------------------------------------------
class ResearchState(TypedDict):
    """
    State definition for the research workflow.
    """
    # 1. The original research query entered by the user
    question: str

    # 2. The list of sub-questions generated by the planner node
    sub_questions: List[str]

    # 3. Live search results collected by the researcher node (Phase 3)
    search_results: List[dict]
