from typing import TypedDict, List


# -----------------------------------------------------------------------------
# ResearchState: The Central Memory of our Agent Graph
# -----------------------------------------------------------------------------
# In LangGraph, "State" is a shared dictionary that travels from node to node.
# Each node reads what it needs from the state, does some work (like planning,
# searching, extracting, or fact-checking), and returns new/updated values.
# -----------------------------------------------------------------------------
class ResearchState(TypedDict):
    """
    State definition for the research workflow.
    """
    # 1. The original research query entered by the user
    question: str

    # 2. The list of sub-questions generated by the planner node
    sub_questions: List[str]

    # 3. Live search results collected by the web_researcher node (Phase 3)
    search_results: List[dict]

    # 4. Relevant passages retrieved from uploaded documents (Phase 4 & 5)
    document_results: List[dict]

    # 5. Atomic claims and facts extracted from all sources (Phase 6)
    evidence: List[dict]

    # 6. Claims audited with verification verdicts and confidence scores (Phase 7)
    verified_evidence: List[dict]
