from app.graph.state import ResearchState
from app.services.rag import search_documents


# -----------------------------------------------------------------------------
# Document Retriever Node (Phase 5)
# -----------------------------------------------------------------------------
# This node represents our second research branch in LangGraph!
# While the Web Researcher is browsing DuckDuckGo, this node searches
# our local vector store for relevant passages in uploaded documents.
# -----------------------------------------------------------------------------
def document_retriever_node(state: ResearchState) -> dict:
    """
    Reads the sub-questions generated by the Planner and searches the
    vector database of uploaded documents using cosine similarity.
    """
    sub_questions = state.get("sub_questions", [])
    collected_docs = []

    print(f"\n[Doc Retriever Node] Searching uploaded documents for {len(sub_questions)} sub-questions...")

    for i, sub_q in enumerate(sub_questions, 1):
        # Search vector store for this specific sub-question (top 2 passages per question)
        matches = search_documents(query=sub_q, top_k=2)

        for item in matches:
            collected_docs.append({
                "sub_question": sub_q,
                "doc_id": item["doc_id"],
                "title": item["title"],
                "chunk_id": item["chunk_id"],
                "chunk_text": item["chunk_text"],
                "score": item["score"]
            })

    print(f"[Doc Retriever Node] Finished document search. Found {len(collected_docs)} relevant passages.\n")

    # LangGraph automatically merges this dictionary into the state
    return {"document_results": collected_docs}
